Repository wecode-bootcamp-korea/27-2nd-GuysHouse-backend, pull requests merged in 2021-12, with the labels that each got.

#2 CREATED : feature/models
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  guyshouse/settings.py
  programs/__init__.py
  programs/admin.py
  programs/apps.py
  programs/migrations/0001_initial.py
  programs/migrations/0002_initial.py
  programs/migrations/__init__.py
  programs/models.py
  programs/tests.py
  programs/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#3 Program-Category 중간테이블 작성
  programs/migrations/0001_initial.py
  programs/migrations/0002_initial.py
  programs/models.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#5 User 테이블에 kakao_id 컬럼값 추가
  programs/migrations/0001_initial.py
  programs/migrations/0002_initial.py
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: Accepted

#7 Program 앱의 models.py 수정
  programs/migrations/0001_initial.py
  programs/migrations/0002_auto_20211217_1713.py
  programs/models.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#4 Program 앱의 ProgramView 작성
  guyshouse/settings.py
  guyshouse/urls.py
  programs/tests.py
  programs/urls.py
  programs/views.py
Labels: Status: 리뷰 요청

#11 파일업로더 모듈화
  guyshouse/settings.py
  programs/file_handler.py
  programs/views.py
Labels: Status: 리뷰 요청

#10 ProgramListView 카테고리 필터링 기능 구현 (메인페이지)
  guyshouse/settings.py
  programs/migrations/0001_initial.py
  programs/migrations/0002_initial.py
  programs/urls.py
  programs/views.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#13 ProgramView GET메서드 추가
  programs/tests.py
  programs/views.py
  requirements.txt
Labels: Status: 리뷰 요청

#12 Create : ReserveView
  programs/tests.py
  programs/urls.py
  programs/views.py
Labels: Status: 리뷰 요청

#6 kakao signin view 작성
  core/utils/decorator.py
  core/utils/kakao.py
  guyshouse/settings.py
  guyshouse/urls.py
  programs/migrations/0001_initial.py
  programs/migrations/0002_initial.py
  programs/views.py
  users/migrations/0001_initial.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 수정 요청
